-- Stable review test data. Safe to run once; titles are unique.
INSERT INTO contents (`type`, title, description, cover_url, category, tags, status, content_status, reject_reason, view_count, play_count, unique_view_count, like_count, favorite_count, share_count, comment_count, danmaku_count, sort_order, admin_remark, created_by, updated_by, submitted_at, reviewed_at, reviewed_by)
SELECT IF(n % 2 = 1, 1, 2), CONCAT('REVIEW_PENDING_', LPAD(n, 2, '0')), CONCAT('Pending review test content ', n), CONCAT('https://picsum.photos/seed/pending', n, '/800/450'), IF(n % 2 = 1, 'DRAMA', 'INTERACTIVE'), 'TEST,PENDING', 0, 1, NULL, n * 100, n * 70, n * 90, n, 0, 0, 0, 0, n, 'REVIEW_TEST', 2, 2, NOW(), NULL, NULL
FROM (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20) nums
WHERE NOT EXISTS (SELECT 1 FROM contents c WHERE c.title = CONCAT('REVIEW_PENDING_', LPAD(n, 2, '0')));

INSERT INTO contents (`type`, title, description, cover_url, category, tags, status, content_status, reject_reason, view_count, play_count, unique_view_count, like_count, favorite_count, share_count, comment_count, danmaku_count, sort_order, admin_remark, created_by, updated_by, submitted_at, reviewed_at, reviewed_by)
SELECT IF(n % 2 = 1, 1, 2), CONCAT('REVIEW_REJECTED_', LPAD(n, 2, '0')), CONCAT('Rejected review test content ', n), CONCAT('https://picsum.photos/seed/rejected', n, '/800/450'), IF(n % 2 = 1, 'DRAMA', 'INTERACTIVE'), 'TEST,REJECTED', 0, 7, CONCAT('TEST_REJECT_REASON_', LPAD(n, 2, '0')), n * 120, n * 80, n * 100, n, 0, 0, 0, 0, n, 'REVIEW_TEST', 2, 2, NOW(), NOW(), 1
FROM (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20) nums
WHERE NOT EXISTS (SELECT 1 FROM contents c WHERE c.title = CONCAT('REVIEW_REJECTED_', LPAD(n, 2, '0')));
